name: 'PHPStan Tests'
on:
  pull_request:
    paths:
      - 'src/**.php'
      - '*.php'
jobs:
  phpstan:
    strategy:
      matrix:
        phpVersion:
          - 70400
          - 80000
          - 80100
          - 80200
          - 80300
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1000
          submodules: recursive
      # ------------------------------------------------------------------------------
      # Set up PHP
      # ------------------------------------------------------------------------------
      - name: Configure PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - name: Install vendor
        run: composer i --ignore-platform-reqs
      # ------------------------------------------------------------------------------
      # Set up Wordpress
      # ------------------------------------------------------------------------------
      - name: Install WP CLI
        run: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
      - name: Install WP Core
        run: php wp-cli.phar core download --path=wpdemo.test --allow-root
      # ------------------------------------------------------------------------------
      # Run the PHPStan tests
      # ------------------------------------------------------------------------------
      - name: Convert PHPStan Config for Local Paths
        run: |
          sed -i 's/..\/..\/..\/wp-includes/wpdemo.test\/wp-includes/g' phpstan.neon 
      - name: Convert PHPStan Config for PHP Versions
        run: |
          sed -i 's/70400/${{ matrix.phpVersion }}/g' phpstan.neon
      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse
