name: 'Codeception Tests'
on: [pull_request]
jobs:
  test:
    strategy:
      matrix:
        # Start with something easy.
        suite: [ 'wpunit' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive
      - name: Checkout automation tools
        uses: actions/checkout@v2
        with:
          repository: moderntribe/tric
          ref: main
          path: tric
          fetch-depth: 1
      - name: Add tric to the PATH
        run: echo "PATH=${GITHUB_WORKSPACE}/../tric:$PATH" >> $GITHUB_ENV
      - name: Set run_context() for tric
        run: echo "TRIC=1" >> $GITHUB_ENV
      - name: Start ssh-agent
        run: |
          mkdir -p "${HOME}/.ssh";
          ssh-agent -a /tmp/ssh_agent.sock;
      - name: Export SSH_AUTH_SOCK env var
        run: echo "SSH_AUTH_SOCK=/tmp/ssh_agent.sock" >> $GITHUB_ENV
      - name: Set up tric for CI
        run: |
          cd ${GITHUB_WORKSPACE}/..
          tric here
          tric interactive off
          tric build-prompt off
          tric xdebug off
          tric debug on
          tric info
          tric config
      - name: Set up Common
        run: |
          docker network prune -f
          tric use the-events-calendar/common
          tric composer install --no-dev
      - name: Set up The Events Calendar
        run: |
          tric use the-events-calendar
          tric composer install
      - name: Init the WordPress container
        run: tric up wordpress
      - name: Run suite tests
        run: tric run ${{ matrix.suite }} --debug

